-- Criação da tabela `user`
CREATE TABLE user (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL
) ENGINE = INNODB;

-- Criação da tabela `notes`
CREATE TABLE notes (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    body VARCHAR(255) NOT NULL,
    user_id INT(11) NOT NULL,
    CONSTRAINT fk_user__notes_id FOREIGN KEY (user_id)
        REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB;